services:
  antifraud:
    build:
      context: antifraud-service
      dockerfile: Dockerfile
    container_name: app_antifraud
    depends_on:
      - transaction
      - broker
    networks:
      - broker-network

  transaction:
    container_name: app_transaction
    hostname: transaction
    build:
      context: transaction-service
      dockerfile: Dockerfile
    depends_on:
      database_pg:
        condition: service_healthy
      broker:
        condition: service_healthy
    # env_file: transaction-service/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    ports:
      - ${PORT}:4000
    networks:
      - prisma-network
      - broker-network
