services:
  antifraud:
    build:
      context: antifraud-service
      dockerfile: Dockerfile
    container_name: app_antifraud
    depends_on:
      - transaction
      - broker
    networks:
      - broker-network
